// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "CatCalendar",
    platforms: [
        .iOS("17.2")
    ],
    products: [
        .iOSApplication(
            name: "CatCalendar",
            targets: ["AppModule"],
            bundleIdentifier: "catcal",
            teamIdentifier: "PX8DYSY5X5",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .calendar),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .appTransportSecurity(configuration: .init(
                    exceptionDomains: [
                        .init(
                            domainName: "https://api.sunrise-sunset.org",
                            includesSubdomains: true,
                            exceptionAllowsInsecureHTTPLoads: true
                        ),
                        .init(
                            domainName: "https://api.ipgeolocation.io",
                            includesSubdomains: true,
                            exceptionAllowsInsecureHTTPLoads: true
                        ),
                        .init(
                            domainName: "https://api.sunrise-sunset.org",
                            includesSubdomains: true,
                            exceptionAllowsInsecureHTTPLoads: true
                        ),
                        .init(
                            domainName: "https://api.openai.com",
                            includesSubdomains: true,
                            exceptionAllowsInsecureHTTPLoads: true
                        )
                    ]
                )),
                .outgoingNetworkConnections()
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/scinfu/SwiftSoup", "2.7.0"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "SwiftSoup", package: "SwiftSoup")
            ],
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
